import Head from "next/head";
import { Inter } from "next/font/google";
import LandingIntro from "@/components/layout/landing-intro";
import GradientColon from "@/components/ui/gradient-colon";
import { Project } from "@/components/layout/featured-projects";
import LandingAbout, { Skill } from "@/components/layout/landing-about";
import { GetStaticProps, GetStaticPropsResult } from "next";
import dynamic from "next/dynamic";
import LazyLoad from "@/components/utils/LazyLoad";

const DynamicFeaturedProjects = dynamic(
    import("@/components/layout/featured-projects")
);
const DynamicLandingAbout = dynamic(
    import("@/components/layout/landing-about"),
    { ssr: false }
);
const inter = Inter({ subsets: ["latin"] });

interface HomePageProps {
    whatIdo: Skill[];
    projects: Project[];
}

export default function Home({ whatIdo, projects }: HomePageProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <LandingIntro />
                <GradientColon />
                <LazyLoad>
                    <DynamicFeaturedProjects projects={projects} />
                </LazyLoad>
                <LazyLoad>
                    <DynamicLandingAbout whatIdo={whatIdo} />
                </LazyLoad>
            </main>
        </>
    );
}
export const getStaticProps: GetStaticProps<HomePageProps> = async (): Promise<
    GetStaticPropsResult<HomePageProps>
> => {
    const whatIdo = [
        {
            title: "Typescript",
            image: "/images/ts-logo-128.png",
        },
        {
            title: "React",
            image: "/images/react2.png",
        },
        {
            title: "Javascript",
            image: "/me.png",
        },
        {
            title: "CSS",
            image: "/me.png",
        },
    ] as Skill[];

    const projects = [
        {
            title: "Project Title",
            description:
                "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            image: "/project.jpeg",
            link: "",
            tags: ["React", "Next.js"],
        },
        {
            title: "Project Title",
            description:
                "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            image: "/project.jpeg",
            link: "",
            tags: ["React", "Next.js"],
        },
    ] as Project[];

    return {
        props: {
            whatIdo,
            projects,
        },
    };
};
